# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


ImputeKnn <- function(knn_idx, ref_idx, cell_idx, gene_idx, dat, impute_dat, w_mat_,  transpose_input, transpose_output) {
  invisible(.Call('_scrattch_hicat_ImputeKnn', PACKAGE = 'scrattch.hicat',
                  knn_idx, ref_idx, cell_idx, gene_idx, dat, impute_dat, w_mat_,  transpose_input, transpose_output))
}

